module.exports = {
	"defaultDate": null,
	"defaultDates": {
		"startDate": null,
		"endDate": null
	},
	"selectDefaultDate": true,
	"rangeSelect": false,
	"alwaysFilled": false,
	"minDate": null,
	"maxDate": null,
	"disabledDates": [],
	"disabledClass": "form-item--disabled",
	"monthsToShow": 2,
	"monthNames": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", ""],
	"monthNamesShort": ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec", ""],
	"dayNames": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
	"dayNamesShort": ["sun", "mon", "tue", "wed", "thu", "fri", "sat"],
	"dayNamesMin": ["sun", "mon", "tue", "wed", "thu", "fri", "sat"],
	"dateFormat": "dd.mm.yyyy",
	"prevText": "&#x3cPrevious",
	"prevStatus": "Show previous month",
	"prevJumpText": "&#x3c&#x3c",
	"prevJumpStatus": "",
	"nextText": "Next&#x3e;",
	"nextStatus": "Show next month",
	"nextJumpText": "&#x3e;&#x3e;",
	"nextJumpStatus": "",
	"todayText": "Choose a date",
	"todayStatus": "Show current month",
	"clearText": "Reset",
	"clearStatus": "Reset the current date",
	"closeText": "Close",
	"closeStatus": "Close without changes",
	"yearStatus": "Show another year",
	"monthStatus": "Show another month",
	"weekText": "Week",
	"weekStatus": "The year's week",
	"dayStatus": "'Choose' D, M d",
	"defaultStatus": "Choose a date",
	"applyText": "Apply",
	"placeholder": "Select any date range",
	"monthHeaderFormat": null
};